### ISSUE TITLE
Use `Enum` instead of string literals for `vtype` 

### ISSUE THREAD

**Issue by kjartan-at-bravos** [staadecker/pyoframe#13]
For instance,

`import polars as pl`
`import pyoframe as pf`
`m = pf.Model()`
`m.x = pf.Variable(pl.DataFrame([1,2,3]), vtype=pf.BINARY)`

**Comment by staadecker** [comment]
Done. 

Although you'd need to do `pf.VType.BINARY`. (I like to do `from pyoframe import ...` to make the code less verbose)
