### ISSUE TITLE
Discussion: how to design addition

### ISSUE THREAD

**Issue by staadecker** [staadecker/pyoframe#16]
There has been multiple ideas / discussions about handling addition properly and I wanted to document them here as decisions are made.

## Handling missing dimensions

The current plan is to require the user to call `add_dim()` when increasing the dimensions of an expression via addition. Without `add_dim()` an error will be thrown.

### Example

```python
>>> import polars as pl
>>> food_cost = pl.DataFrame({
        "month": ["Jan", "Feb", "Mar", "Jan", "Feb", "Mar"], 
        "year":     [2023, 2023, 2023, 2024, 2024, 2024],
        "monthly_cost": [1000, 1010, 1020, 1030, 1040, 1050]
    }).to_expr()
>>> rent = pl.DataFrame({
        "year": [2023, 2024],
        "monthly_cost": [1000, 1100]
    }).to_expr()

# This should throw an error
>>> food_cost + rent

# This shouldn't
>>> food_cost + rent.add_dim("month")
```

## Handling unmatched indices

What happens if indices exist in one side of the some but not the other? For example, in the previous example, if one of the two tables contained extra years.

I propose the default is an error is thrown (#7). However there should be two alternatives.

`.keep_unmatched()`: If there are unmatched rows (rows where the index exists in only one of the two tables), these are kept.

`.drop_unmatched()`: Only indices that are in common between both dataframes are kept.

### Example

```python3
>>> food_cost = pl.DataFrame({
        "month": ["Jan", "Feb", "Mar", "Jan", "Feb", "Mar", "Jan"], 
        "year":     [2023, 2023, 2023, 2024, 2024, 2024, 2025],
        "monthly_cost": [1000, 1010, 1020, 1030, 1040, 1050, 1060]
    }).to_expr()
>>> rent = pl.DataFrame({
        "year": [2023, 2024],
        "monthly_cost": [1000, 1100]
    }).to_expr()

# This returns an error because food_cost has year=2025 but not rent
>>> food_cost + rent.add_dim("month")

# This is fine and drops (Jan, 2025)
>>> food_cost.drop_unmatched() + rent.add_dim("month")

# This is fine and keeps (Jan, 2025)
>>> food_cost.keep_unmatched() + rent.add_dim("month")

# What about the reverse situation
>>> food_cost = pl.DataFrame({
        "month": ["Jan", "Feb", "Mar", "Jan", "Feb", "Mar"], 
        "year":     [2023, 2023, 2023, 2024, 2024, 2024],
        "monthly_cost": [1000, 1010, 1020, 1030, 1040, 1050]
    }).to_expr()
>>> rent = pl.DataFrame({
        "year": [2023, 2024, 2025],
        "monthly_cost": [1000, 1100, 1200]
    }).to_expr()

# The behavior is the same... except for this case!
>>> cost_of_housing + cost_of_taxes.add_dim("month").keep_unmatched()

# The above line throws an error since it is impossible to know which month should be applied in the added "month" dimensions, when there is no year match.
# Basically, `add_dim()` con only be used when there are no unmatched indices or when using `.drop_unmatched()`
```

### Review of expression representation

Each expression is a dataframe with columns (dim1, dim2, dim3, ...) and also columns (__variable_id) and (__coef).

### Approaches to adding

Adding requires performing a concatenation of both dataframes followed by a `group_by(...).sum()` operation. 

(An alternative approach would be doing an outer join on all but the coefficient column, and then summing the coefficient columns using 0 instead of null. However this is almost surely slower and has no advantage.)

The concatenation approach is great however it doesn't check for unmatched indices. To check for unmatched indices, an outer join has to be done on the dimension columns. Rows containing `null` reveal unmatched indices. Additionally, if using `drop_unmatched()`, an inner join has to be performed on each operand individually to keep only the values in common. Finally, if adding a dimension a join needs to also be performed.

### Unmatched strategy types

Each term would have an `unmatched_strategy` property which is an enum with one of three options.

`error`: This is the default and means an error should be thrown if the term has an unmatched row.
`drop`: Enabled via `.drop_unmatched()` this means unmatched rows are ignored (dropped).
`keep`: Enabled via `.keep_unmatched()` this means unmatched rows are kept (equivalent to giving a default `0` value to the other summation terms).

### Proposed implementation decision tree

Scenario | `add_dim()` | Left and right terms' unmatched strategy |  Operation required before concatenation 
--- | --- | --- | --- 
1 (Default) | None | error with error | 1 outer join to check for unmatched
2 | None | drop with drop |  Two inner joins to remove unmatched on each term
3 | None | keep with keep |  None
4 | None | drop with error |  Filter drop term via right join with check
5 | None | keep with error |  Check error term via right join on keep term
6 | None | drop with keep |  Same as 4 but without check
7 | One of the terms | error with error | Outer join on `.add_dim()` term with check
8 | Both of the terms | error with error | Outer join on each `.add_dim()` term with check

TODO continue table for other cases

## Performance and multi-element additions

The `.concat()` operation can be applied to a sum of multiple elements however the `.join()` cannot. Therefore, a sped-up addition for multi-element sums can only be done in scenario 3 (no added dimensions and `.keep_unmatched()`)

One possibility is adding a configuration flag to the library called `disable_unmatched_checks`. If it is set to `True`, then `.keep_unmatched()` would become the default and a faster addition would be performed. Should this be implemented? If so, it could then be worthwhile to implement a `LazySumExpression` that allows for summation terms to accumulate and only computes the summation when it's needed.

Note that the performance speeds-up reported in #15 are not the full picture since they omitted the `.group_by().sum()` operation.

## Implementation plan

For now, I suggest that I implement the `add_dim()` separately which (although less optimal) is a lot simpler.

**Comment by kjartan-at-bravos** [comment]
Great ideas! 

###  About handling missing dimensions
I prefer the explicit broadcasting involved in `add_dim()` to silently adding "missing" dimensions as is done in GAMS. In GAMS the broadcasting remains obvious, since the expressions include the dimensions of all variables (and not just their names).

### About unmatched indices 
In GAMS, values for missing indexes are zero or non-existing. Having as default a similar behavior in pyoframe is reasonable,. This is an argument for using scenario 3 as default, and is the most efficient of the alternatives, since it does not require any joins before concatenation.  However, I am also here in favor of making it explicit when unmatched indices should be ignored. So I support having the more cautious strategy of Scenario 1 as default.
 
Possibly, the case of `drop_unmatched` is sufficient infrequent that we can leave it to the user can do the match manually.
`food_cost.filter(pl.col("year").is_in(rent.data.select("year"))) + rent.add_dim("month")`

### Speed improvement of multi-element additions
I redid the example of #15 
```
In [22]: m = pf.Model()
    ...: m.x = pf.Variable(pl.DataFrame({"p": np.arange(2000)}), pl.DataFrame({"t": np.arange(200)}))
    ...: m.y = pf.Variable(pl.DataFrame({"p": np.arange(2000)}), pl.DataFrame({"t": np.arange(200)}))
    ...: m.z = pf.Variable(pl.DataFrame({"p": np.arange(2000)}), pl.DataFrame({"t": np.arange(200)}))
    ...: %timeit m.x + m.y + m.z
    ...: %timeit pl.concat([m.x.to_expr().data + m.y.to_expr().data + m.z.to_expr().data], how="vertical_relaxed").group_by(["p", "t", "__variable_id"]).sum()
495 ms ± 36.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
102 ms ± 5.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```

**Comment by staadecker** [comment]
Aha thank you for re-running the performance test! The 5x speedup is significant and good to know! 

Seems like we agree to use `add_dim()`. Regarding, `drop_unmatched` I think it's actually a relatively common use case. E.g. from the nutrition we could do

```python3
m.max_nutrients = sum("food", m.Buy * food_nutrients).drop_unmatched() <= max_nutrient
```

instead of needing

```python3
m.max_nutrients = sum("food", m.Buy * food_nutrients.within(max_nutrient)) <= max_nutrient
```

to ensure a constraint is only created when max_nutrient exists.

I'm also hesitant to allow for a default of zero (without an explicit `keep_unmatched`) since it would mean that the following expression:

```python3
m.max_nutrients = sum("food", m.Buy * food_nutrients) <= max_nutrient
```

sets an upperbound of 0 whenever max_nutrient is undefined, which is an unwanted behaviour. I rather this expression return an error.

I think we can default to requiring the explicit `keep_unmatched` but with a system-wide setting

`Config.disable_unmatched_checks = False`

This flag could be set to True once a model has been properly tested.
