### ISSUE TITLE
Improved .to_str(model)

### ISSUE THREAD

**Issue by kjartan-at-bravos** [staadecker/pyoframe#2]
It would be great if the output of an expression was not this:

+1.0 kappa_py[7,5,3,9] +1.0 kappa_py[7,5,1,9] +1.0 kappa_py[7,5,2,9] +1.0 kappa_py[7,5,0,9] 

But also included the "index" of the expression:

[7, 5, 9]: +1.0 kappa_py[7,5,3,9] +1.0 kappa_py[7,5,1,9] +1.0 kappa_py[7,5,2,9] +1.0 kappa_py[7,5,0,9]  

Also, the dimensions of the expression and their names at the top of the output would be great.

**Comment by staadecker** [comment]
Done!

```python
>>> from pyoframe import Variable, Model
>>> import pandas as pd
>>> df = pd.DataFrame({"dim1": [1, 2, 3], "dim2": [3,4,5]})
>>> m = Model()
>>> m.test_var = Variable(df)
>>> m.test_var * 2
<Expression size=3 dimensions={'dim1': 3, 'dim2': 3} terms=3>
[1,3]: 2.0 test_var[1,3]
[2,4]: 2.0 test_var[2,4]
[3,5]: 2.0 test_var[3,5]
```
